/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.unipacifico.presentacion;

import co.edu.unipacifico.controlador.*;
import co.edu.unipacifico.modelo.*;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class GUIEnviarMensaje extends javax.swing.JFrame {

    private final IControladorLinea controladorLinea = new ControladorLinea();

    /**
     * Creates new form EnviarMensaje
     */
    public GUIEnviarMensaje() {
        initComponents();
        setLocationRelativeTo(null);
        llenarCombox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textoEnviarMensaje = new javax.swing.JLabel();
        comboxLineas = new javax.swing.JComboBox<>();
        textoSeleccionarLinea = new javax.swing.JLabel();
        textoEscribirMensaje = new javax.swing.JLabel();
        textoNumeroReceptor = new javax.swing.JLabel();
        campoReceptor = new javax.swing.JTextField();
        botonEnviarMensaje = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textoEnviarMensaje.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        textoEnviarMensaje.setText("ENVIAR MENSAJE");
        jPanel1.add(textoEnviarMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 15, -1, -1));

        comboxLineas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxLineasActionPerformed(evt);
            }
        });
        jPanel1.add(comboxLineas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        textoSeleccionarLinea.setBackground(new java.awt.Color(204, 204, 204));
        textoSeleccionarLinea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textoSeleccionarLinea.setText("Seleccione la linea emisora:");
        jPanel1.add(textoSeleccionarLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        textoEscribirMensaje.setBackground(new java.awt.Color(204, 204, 204));
        textoEscribirMensaje.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        textoEscribirMensaje.setText("Escriba el mensaje:");
        jPanel1.add(textoEscribirMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 170, -1, -1));

        textoNumeroReceptor.setBackground(new java.awt.Color(204, 204, 204));
        textoNumeroReceptor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textoNumeroReceptor.setText("Escriba el numero receptor:");
        jPanel1.add(textoNumeroReceptor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));
        jPanel1.add(campoReceptor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 140, -1));

        botonEnviarMensaje.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonEnviarMensaje.setText("Enviar");
        botonEnviarMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEnviarMensajeActionPerformed(evt);
            }
        });
        jPanel1.add(botonEnviarMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 210, 90, 40));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 210, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEnviarMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEnviarMensajeActionPerformed

        String emisor = comboxLineas.getSelectedItem().toString();
        String receptor = campoReceptor.getText();
        String mensaje = jTextField1.getText();
        
        if (emisor.isBlank() || receptor.isBlank() || mensaje.isBlank()) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos!");
        } else if (receptor.length() < 10) {
            JOptionPane.showMessageDialog(null, "El numero del receptor es inferior a 10 digitos!");
        } else if (receptor.length() > 10) {
            JOptionPane.showMessageDialog(null, "El numero del receptor es superior a 10 digitos!");
        } else {
            try {
                controladorLinea.realizarMensaje(emisor, receptor, mensaje);
                JOptionPane.showMessageDialog(null, "El mensaje fue enviado con exito!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Error al enviar mensaje:\n" + ex.getMessage());
            }
        }
    }//GEN-LAST:event_botonEnviarMensajeActionPerformed

    public void llenarCombox() {
        try {
            for (LineaTelefonica linea : controladorLinea.listarLineasTelefonicas()) {
                comboxLineas.addItem(linea.getNumeroLinea());
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error al listar lineas:\n" + ex.getMessage());
        }
    }

    private void comboxLineasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxLineasActionPerformed

    }//GEN-LAST:event_comboxLineasActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEnviarMensaje;
    private javax.swing.JTextField campoReceptor;
    private javax.swing.JComboBox<String> comboxLineas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel textoEnviarMensaje;
    private javax.swing.JLabel textoEscribirMensaje;
    private javax.swing.JLabel textoNumeroReceptor;
    private javax.swing.JLabel textoSeleccionarLinea;
    // End of variables declaration//GEN-END:variables
}
