/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.unipacifico.presentacion;

import co.edu.unipacifico.controlador.*;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class GUILineaTelefonica extends javax.swing.JFrame {

    private final IControladorLinea controladorLinea = new ControladorLinea();

    /**
     * Creates new form GUILineaTelefonica
     */
    public GUILineaTelefonica() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        PanelFondoNegro = new javax.swing.JPanel();
        Texto_Menu = new javax.swing.JLabel();
        Texto_LineaTelefonica = new javax.swing.JLabel();
        Menu_CustarBitacoraPorNumero = new javax.swing.JLabel();
        Menu_RegistrarLinea = new javax.swing.JLabel();
        Menu_EnviarMensaje = new javax.swing.JLabel();
        Menu_RealizarLlamada = new javax.swing.JLabel();
        Menu_CustarBitacora = new javax.swing.JLabel();
        Menu_Salir = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("GestionLineaTelefonica"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelFondo.setBackground(new java.awt.Color(69, 73, 74));
        PanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelFondoNegro.setBackground(new java.awt.Color(51, 51, 51));
        PanelFondoNegro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Texto_Menu.setBackground(new java.awt.Color(204, 204, 204));
        Texto_Menu.setFont(new java.awt.Font("Segoe UI", 1, 54)); // NOI18N
        Texto_Menu.setText("MENU");
        PanelFondoNegro.add(Texto_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 10, -1, -1));

        Texto_LineaTelefonica.setBackground(new java.awt.Color(204, 204, 204));
        Texto_LineaTelefonica.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Texto_LineaTelefonica.setText("LINEA TELEFONICA");
        PanelFondoNegro.add(Texto_LineaTelefonica, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 70, -1, -1));

        Menu_CustarBitacoraPorNumero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unipacifico/imagenes/book-content-solid-48.png"))); // NOI18N
        Menu_CustarBitacoraPorNumero.setText("CONSULTAR BITACORA POR NUMERO");
        Menu_CustarBitacoraPorNumero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_CustarBitacoraPorNumeroMouseClicked(evt);
            }
        });
        PanelFondoNegro.add(Menu_CustarBitacoraPorNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 290, 40));

        Menu_RegistrarLinea.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Menu_RegistrarLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unipacifico/imagenes/list-plus-regular-40.png"))); // NOI18N
        Menu_RegistrarLinea.setText("REGISTRAR LINEA");
        Menu_RegistrarLinea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_RegistrarLineaMouseClicked(evt);
            }
        });
        PanelFondoNegro.add(Menu_RegistrarLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 290, 50));

        Menu_EnviarMensaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unipacifico/imagenes/message-regular-60.png"))); // NOI18N
        Menu_EnviarMensaje.setText("ENVIAR MENSAJE");
        Menu_EnviarMensaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_EnviarMensajeMouseClicked(evt);
            }
        });
        PanelFondoNegro.add(Menu_EnviarMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 290, 40));

        Menu_RealizarLlamada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unipacifico/imagenes/phone-call-regular-48.png"))); // NOI18N
        Menu_RealizarLlamada.setText("REALIZAR LLAMADA");
        Menu_RealizarLlamada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_RealizarLlamadaMouseClicked(evt);
            }
        });
        PanelFondoNegro.add(Menu_RealizarLlamada, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 290, 40));

        Menu_CustarBitacora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unipacifico/imagenes/book-content-regular-48.png"))); // NOI18N
        Menu_CustarBitacora.setText("CONSULTAR BITACORA");
        Menu_CustarBitacora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_CustarBitacoraMouseClicked(evt);
            }
        });
        PanelFondoNegro.add(Menu_CustarBitacora, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 290, 40));

        Menu_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unipacifico/imagenes/exit-regular-48.png"))); // NOI18N
        Menu_Salir.setText("SALIR");
        Menu_Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_SalirMouseClicked(evt);
            }
        });
        PanelFondoNegro.add(Menu_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 290, 40));
        PanelFondoNegro.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 290, 30));

        jSeparator2.setBackground(new java.awt.Color(51, 51, 51));
        PanelFondoNegro.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 290, 30));
        PanelFondoNegro.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 290, 30));
        PanelFondoNegro.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 290, 30));
        PanelFondoNegro.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 290, 30));
        PanelFondoNegro.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 290, 30));

        PanelFondo.add(PanelFondoNegro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 480));

        getContentPane().add(PanelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 477));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Menu_SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_SalirMouseClicked
        JOptionPane.showMessageDialog(null, "Gracias por usar el sistema!", "Salir", JOptionPane.INFORMATION_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_Menu_SalirMouseClicked

    private void Menu_RegistrarLineaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_RegistrarLineaMouseClicked
        new GUIRegistrarLinea().setVisible(true);
    }//GEN-LAST:event_Menu_RegistrarLineaMouseClicked

    private void Menu_EnviarMensajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_EnviarMensajeMouseClicked
        try {
            if (!controladorLinea.listarLineasTelefonicas().isEmpty()) {
                new GUIEnviarMensaje().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "No hay lineas registradas!");
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error al realizar mensaje:\n" + ex.getMessage());
        }
    }//GEN-LAST:event_Menu_EnviarMensajeMouseClicked

    private void Menu_RealizarLlamadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_RealizarLlamadaMouseClicked
        try {
            if (!controladorLinea.listarLineasTelefonicas().isEmpty()) {
                new GUIRealizarLlamada().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "No hay lineas registradas!");
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error al realizar llamada:\n" + ex.getMessage());
        }
    }//GEN-LAST:event_Menu_RealizarLlamadaMouseClicked

    private void Menu_CustarBitacoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_CustarBitacoraMouseClicked
        try {
            if (!controladorLinea.consultarBitacoraOperaciones().isEmpty()) {
                new GUIConsultarBitacoraOperaciones().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "No hay registros disponibles!");
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error al consultar bitacora:\n" + ex.getMessage());
        }
    }//GEN-LAST:event_Menu_CustarBitacoraMouseClicked

    private void Menu_CustarBitacoraPorNumeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_CustarBitacoraPorNumeroMouseClicked
        new GUIConsultarBitacoraPorNumero().setVisible(true);
    }//GEN-LAST:event_Menu_CustarBitacoraPorNumeroMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUILineaTelefonica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUILineaTelefonica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUILineaTelefonica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUILineaTelefonica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUILineaTelefonica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Menu_CustarBitacora;
    private javax.swing.JLabel Menu_CustarBitacoraPorNumero;
    private javax.swing.JLabel Menu_EnviarMensaje;
    private javax.swing.JLabel Menu_RealizarLlamada;
    private javax.swing.JLabel Menu_RegistrarLinea;
    private javax.swing.JLabel Menu_Salir;
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JPanel PanelFondoNegro;
    private javax.swing.JLabel Texto_LineaTelefonica;
    private javax.swing.JLabel Texto_Menu;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
