/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.unipacifico.presentacion;

import co.edu.unipacifico.controlador.*;
import co.edu.unipacifico.modelo.*;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class GUIRegistrarLinea extends javax.swing.JFrame {

    private final IControladorLinea controladorLinea = new ControladorLinea();

    /**
     * Creates new form RegistrarLinea
     */
    public GUIRegistrarLinea() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoNegro = new javax.swing.JPanel();
        Texto_RestrarLinea = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        textoNombre = new javax.swing.JLabel();
        botonRegistrar = new javax.swing.JButton();
        textoDocumento = new javax.swing.JLabel();
        campoDocumento = new javax.swing.JTextField();
        textoLineaTelefonica = new javax.swing.JLabel();
        campoLineaTelefonica = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("VentanaRegistarLinea"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FondoNegro.setBackground(new java.awt.Color(51, 51, 51));
        FondoNegro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Texto_RestrarLinea.setBackground(new java.awt.Color(153, 153, 0));
        Texto_RestrarLinea.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Texto_RestrarLinea.setText("REGISTRAR LINEA");
        FondoNegro.add(Texto_RestrarLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        campoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreActionPerformed(evt);
            }
        });
        FondoNegro.add(campoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 220, -1));

        textoNombre.setBackground(new java.awt.Color(204, 204, 204));
        textoNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textoNombre.setText("Nombre:");
        FondoNegro.add(textoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        botonRegistrar.setText("Registrar Linea");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });
        FondoNegro.add(botonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        textoDocumento.setBackground(new java.awt.Color(204, 204, 204));
        textoDocumento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textoDocumento.setText("Documento:");
        FondoNegro.add(textoDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        campoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDocumentoActionPerformed(evt);
            }
        });
        FondoNegro.add(campoDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 220, -1));

        textoLineaTelefonica.setBackground(new java.awt.Color(204, 204, 204));
        textoLineaTelefonica.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textoLineaTelefonica.setText("Linea Telefonica:");
        FondoNegro.add(textoLineaTelefonica, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        campoLineaTelefonica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoLineaTelefonicaActionPerformed(evt);
            }
        });
        FondoNegro.add(campoLineaTelefonica, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 220, -1));

        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        FondoNegro.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 110, -1));
        jButton1.getAccessibleContext().setAccessibleName("");

        getContentPane().add(FondoNegro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreActionPerformed

    private void campoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDocumentoActionPerformed

    private void campoLineaTelefonicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoLineaTelefonicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoLineaTelefonicaActionPerformed

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed

        String nombre = campoNombre.getText();
        String documento = campoDocumento.getText();
        String numeroLinea = campoLineaTelefonica.getText();
        Afiliado afiliado = new Afiliado(nombre, documento);
        
        if (nombre.isBlank() || documento.isBlank() || numeroLinea.isBlank()) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos!");
        } else if (numeroLinea.length() < 10) {
            JOptionPane.showMessageDialog(null, "El numero de linea es inferior a 10 digitos!");
        } else if (numeroLinea.length() > 10) {
            JOptionPane.showMessageDialog(null, "El numero de linea es superior a 10 digitos!");
        } else {
            try {
                controladorLinea.registrarLinea(numeroLinea, afiliado);
                JOptionPane.showMessageDialog(null, "La linea fue agregada con exito!", "Registro de linea", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Error al registrar al archivo:\n" + ex.getMessage());
            }
        }
    }//GEN-LAST:event_botonRegistrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        campoNombre.setText("");
        campoDocumento.setText("");
        campoLineaTelefonica.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoNegro;
    private javax.swing.JLabel Texto_RestrarLinea;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JTextField campoDocumento;
    private javax.swing.JTextField campoLineaTelefonica;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel textoDocumento;
    private javax.swing.JLabel textoLineaTelefonica;
    private javax.swing.JLabel textoNombre;
    // End of variables declaration//GEN-END:variables
}
